### ISSUE TITLE
Subir ficheros *.c

### ISSUE THREAD

**Issue by yzacarias** [yzacarias/lab8#1]
Hola vamos a subir los ficheros *.c del proyecto @ostua @dragoonx360 @dancaschi

**Comment by dragoonx360** [comment]
Perfecto @yzacarias, lo hacemos así.
Termino los archivos y los subo para que los revises.
Un saludo

**Comment by dancaschi** [comment]
Gracias @yzacarias .

**Comment by yzacarias** [comment]
Ok, pues espero a que subáis los archivos de proyecto

**Comment by yzacarias** [comment]
Vale, creado dos directorios. mover los ficheros fuentes y en img cargar un par de imagenes cada uno

**Comment by yzacarias** [comment]
olvidaros del ultimo comentario. cierro este asunto
